// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDjeRoIjKR_d-ifyU6odVWD82mNWaZbKw',
    appId: '1:941563890966:web:8c87f034b4270a40865437',
    messagingSenderId: '941563890966',
    projectId: 'health-care-app-fe66a',
    authDomain: 'health-care-app-fe66a.firebaseapp.com',
    storageBucket: 'health-care-app-fe66a.firebasestorage.app',
    measurementId: 'G-CSQL9PDTWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ShYTm77GETnXTmUQIt_CB7snBXJ724U',
    appId: '1:941563890966:android:1de20a9c9d7f99d3865437',
    messagingSenderId: '941563890966',
    projectId: 'health-care-app-fe66a',
    storageBucket: 'health-care-app-fe66a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByuie66McYvTC16vRkFjxZvB8mQJTlD9E',
    appId: '1:941563890966:ios:bdb6646cac99d96c865437',
    messagingSenderId: '941563890966',
    projectId: 'health-care-app-fe66a',
    storageBucket: 'health-care-app-fe66a.firebasestorage.app',
    iosClientId: '941563890966-fve0i14mun9s6msegrgrefk20t4k90ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByuie66McYvTC16vRkFjxZvB8mQJTlD9E',
    appId: '1:941563890966:ios:bdb6646cac99d96c865437',
    messagingSenderId: '941563890966',
    projectId: 'health-care-app-fe66a',
    storageBucket: 'health-care-app-fe66a.firebasestorage.app',
    iosClientId: '941563890966-fve0i14mun9s6msegrgrefk20t4k90ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDjeRoIjKR_d-ifyU6odVWD82mNWaZbKw',
    appId: '1:941563890966:web:03230aeaf96e5098865437',
    messagingSenderId: '941563890966',
    projectId: 'health-care-app-fe66a',
    authDomain: 'health-care-app-fe66a.firebaseapp.com',
    storageBucket: 'health-care-app-fe66a.firebasestorage.app',
    measurementId: 'G-57YXLQFP3S',
  );
}
